<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CommentAgg\GetById\" />
    <Folder Include="Product\" />
    <Folder Include="Role\" />
    <Folder Include="Banner\" />
    <Folder Include="Slider\" />
    <Folder Include="User\" />
    <Folder Include="Seller\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Query\Common.Query.csproj" />
    <ProjectReference Include="..\Shop.Infrastructure\Shop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
