<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Sellers\DeleteInventory\" />
    <Folder Include="SiteEntities\Banners\Delete\" />
    <Folder Include="SiteEntities\Sliders\Delete\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\Shop.Domain\Shop.Domain.csproj" />
  </ItemGroup>

</Project>
